### ISSUE TITLE
Fjaxyu#1801 does not add to the list

### ISSUE THREAD

**Issue by fjaxyu** [EcZachly/warzone-app#3]
I keep getting an error message back when I've tried any of the following

- fjaxyu
- Fjaxyu
- fjaxyu#1801
- Fjaxyu#1801
- fjaxyu 1801

This is for battle.net, but I've also tried xbox with no luck too

**Comment by EcZachly** [comment]
Did you link your Battle.net account to your activision account? If you didn't then that's why it didn't work.

**Comment by EcZachly** [comment]
http://www.brshooter.com/gamer/Fjaxyu%231801 

I was able to add it via the CLI

**Comment by fjaxyu** [comment]
https://rapidapi.com/elreco/api/call-of-duty-modern-warfare?utm_source=google&utm_medium=cpc&utm_campaign=Alpha_104860023816&utm_term=warzone%20api_e&gclid=CjwKCAjwkoz7BRBPEiwAeKw3q5j6ZzQ9_DfaVeo9ZvGC_WaDwmRDjm3mGh9zbcLAU5CK9vNUkscB4xoCrpgQAvD_BwE

API does mention this: "You must replace # by %2523"
